### ISSUE TITLE
Keybinding conflict with system key bindings

### ISSUE THREAD

**Issue by aziz** [sahibalejandro/sublime-nav-panel#2]
On mac `super+up` is equivalent on `home`
In general, don't define keybinding as a plugin. Define commands, add them to the command panel and in your Readme instruct the user to define their own keybinding.

**Comment by sahibalejandro** [comment]
You can always change the key binding to your needs.

**Comment by aziz** [comment]
No! Although I can customize the key binding, and I did, your plugin still screw up Sublime's key binding for `home` key on mac which makes sublime pretty unusable. If you want anyone on Mac to use your plugin you should change it to something else. 

You can have OS specific keybindings. look how I've done it on PlainTasks for [Mac](https://github.com/aziz/PlainTasks/blob/master/Default%20%28OSX%29.sublime-keymap), [Windows](https://github.com/aziz/PlainTasks/blob/master/Default%20%28Windows%29.sublime-keymap) and [Linux](https://github.com/aziz/PlainTasks/blob/master/Default%20%28Linux%29.sublime-keymap)

**Comment by sahibalejandro** [comment]
Any key binding on mind?

**Comment by aziz** [comment]
`super+alt+up` is a good one but even that one is taken by sublime itself and gonna upset some users.

```
{ "keys": ["super+alt+up"], "command": "switch_file", "args": {"extensions": ["cpp", "cxx", "cc", "c", "hpp", "hxx", "hh", "h", "ipp", "inl", "m", "mm"]} },
```

As I said, best practice is not to ship with any general keybinding. Instruct users in README on how to do it by providing an example, but let them decide and just add your command as a plugin to the command palette.

**Comment by sahibalejandro** [comment]
I like the "no configuration" approach, so I'll think of a good key binding taking into account your advice.
