### ISSUE TITLE
Broken `sublime-menu` file paths

### ISSUE THREAD

**Issue by ghost** [sahibalejandro/sublime-nav-panel#4]
This package is installed as **Nav Panel.sublime-package** through Package Control, but the `Main.sublime-menu` [file](https://github.com/sahibalejandro/sublime-nav-panel/blob/master/Main.sublime-menu) specifies **NavPanel** (no whitespace) [1] in its paths, resulting in a broken `sublime-menu` file.
I see a number of developers doing this and I don't get why it doesn't fail in their tests before releasing.

[1]
`${packages}/NavPanel/NavPanel.sublime-settings`
`${packages}/NavPanel/Default (OSX).sublime-keymap`

**Comment by sahibalejandro** [comment]
Thanks for the advice, I'll take a look and fix it if needed. :)
